docker container for thank you mail
serlo/infrastructure-images pull request #7
Opened 2023-01-30 16:10 UTC by Entkenntnis

open todo: mail configuration

2023-01-30 22:06 UTC, hugotiburtino requested changes
Let's prepare it for the real deployment.

2023-01-30 22:06 UTC, hugotiburtino commented on container/thankyou-mail/script.js
> +    to: "quinn@serlo.org",
```suggestion
    to: $EMAIL_DISTRIBUTOR
```
If you follow the idea of using a distributor (Verteiler) for it.

2023-01-30 22:06 UTC, hugotiburtino commented on container/thankyou-mail/script.js
> +const users = ["quinn@serlo.org"];
```suggestion
```
Unnecessary in case you prefer to use a email distributor

2023-01-31 11:07 UTC, kulla requested changes

2023-01-31 11:07 UTC, kulla commented on container/thankyou-mail/Dockerfile
> +FROM node:18
```suggestion
FROM node:18-alpine
```

2023-02-07 10:55 UTC, Entkenntnis commented
TODO:

- [ ] use mailing list
- [ ] add new parameters to dockerfile

2023-09-08 08:17 UTC, Entkenntnis commented
outdated

2023-09-08 08:17 UTC, closed without merging